name: DMTP #Dynamic Multi-Modal Trajectory Prediction
ref: models.DMTP
hyperparams:
  layer number: 1
  model dim: 512
  feedforward dim: 128
  classifier dim: 256
  head number: 8
  probabilistic output: True
  number of modes: 10
  manouvre per mode: 3

optimizer: torch.optim.Adam
man loss function: torch.nn.CrossEntropyLoss # This is the loss function to evaluate mode prob estimation
traj loss function: torch.nn.MSELoss
model training function: mstf.DMTP_training
model evaluation function: mstf.DMTP_evaluation
model kpi function: kpis.XMTP_kpis
data type: 'state'
state type: 'wirth'