name: MMnTP #Multi-Modal Manouvre and Trajectory Prediction
ref: models.MMnTP
hyperparams:
  layer number: 1
  model dim: 512
  feedforward dim: 128
  classifier dim: 256
  head number: 8
  probabilistic output: True
  number of modes: 6
  manouvre per mode: 3 # = number of change period+1

optimizer: torch.optim.Adam
man loss function: kpis.MTPM_loss
traj loss function: torch.nn.MSELoss
model training function: mstf.MMnTP_training
model evaluation function: mstf.MMnTP_evaluation
model kpi function: kpis.MMnTP_kpis
data type: 'state'
state type: 'wirth'