name: SMTP #Static Multi-modal Trajectory Prediction
ref: models.SMTP
hyperparams:
  layer number: 1
  model dim: 512
  feedforward dim: 128
  classifier dim: 256
  head number: 8
  probabilistic output: True
  number of modes: 3
  manouvre per mode: 1

optimizer: torch.optim.Adam
man loss function: torch.nn.CrossEntropyLoss # This is the loss function to evaluate mode prob estimation
traj loss function: torch.nn.MSELoss
model training function: mstf.SMTP_training
model evaluation function: mstf.SMTP_evaluation
model kpi function: kpis.MMnTP_kpis
data type: 'state'
state type: 'wirth'