dataset:
  balanced: False
  ablation: False

experiment:
  group: 'miscellaneous'
  cuda: True
  debug_mode: False
  multi_modal_eval: True

training:
  batch_size: 32
  lr: 0.001 # 0.001 #0.0015 #0.000001 0.01#0.00001
  lr_wu: True #True
  lr_wu_batches: 75000
  lr_wu_current_batch: 0
  traj2class_loss_ratio: 1
  lr_decay: 'none' # 'inv-sqrt' or 'none'
  num_epochs: 2 #300
  patience: 2 #300
  skip_validation_epoch: 0
  tr_jump_step: 1  


model:
  man_dec_in: False # If True Manouvre will be inputted to Trajectory decoders
  man_dec_out: True # True means the model can predict manouvre, and manouvre prediction will be considered in loss function calculation
  multi_modal: True
  use_map_features: True
  validation_score: 'rmse' #'Traj Loss'
  lower_better_val_score: True

problem:
  FPS: 5
  MAX_IN_SEQ_LEN: 20
  TGT_SEQ_LEN: 25
  SKIP_SEQ_LEN: 0 # This is to skip final X frame of a track because manouvre labelling depends on future trajectory of a vehicle
